In [2]:
import pandas as pd
import numpy as np

date = pd.read_csv('https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day34-handling-date-and-time/orders.csv')
time = pd.read_csv('https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day34-handling-date-and-time/messages.csv')
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [3]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [4]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [5]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

# Working with Dates

In [6]:
# Converting to date time datatype

date['date'] = pd.to_datetime(date['date'])
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [7]:
date['date_year'] = date['date'].dt.year
date['date_month_no'] = date['date'].dt.month
date['date_month_name'] = date['date'].dt.month_name()
date['date_day'] = date['date'].dt.day # Day number of month
date['date_dayOfWeek'] = date['date'].dt.dayofweek # Day of week
date['date_dow_name'] = date['date'].dt.day_name() # day by name

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dayOfWeek,date_dow_name
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday

In [10]:
# Is weekend ?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Saturday','Sunday']),1,0)
date.drop(columns = ['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dayOfWeek,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

In [13]:
# Extracting week of the year

date['date_week'] = date['date'].dt.isocalendar().week

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dayOfWeek,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

In [14]:
# Extracting Quarter of the Year

date['quarter'] = date['date'].dt.quarter
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dayOfWeek,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

In [16]:
# Extracting Semesters

date['semester'] = np.where(date['quarter'].isin([1,2]),1,2)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dayOfWeek,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

In [17]:
# Extracting Time elapsed between dates

import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 6, 20, 21, 38, 45, 435283)

In [18]:
today - date['date']

0     2384 days 21:38:45.435283
1     2866 days 21:38:45.435283
2     2797 days 21:38:45.435283
3     2499 days 21:38:45.435283
4     2722 days 21:38:45.435283
                 ...
995   2812 days 21:38:45.435283
996   2753 days 21:38:45.435283
997   2601 days 21:38:45.435283
998   2666 days 21:38:45.435283
999   2440 days 21:38:45.435283
Name: date, Length: 1000, dtype: timedelta64[ns]

In [19]:
(today - date['date']).dt.days

0      2384
1      2866
2      2797
3      2499
4      2722
       ...
995    2812
996    2753
997    2601
998    2666
999    2440
Name: date, Length: 1000, dtype: int64

In [23]:
# Months passed

np.round(
    (today - date['date']) / np.timedelta64(1, 'D') / 30.44,
    0
) # 30.44 represents average days per month

0      78.0
1      94.0
2      92.0
3      82.0
4      89.0
       ...
995    92.0
996    90.0
997    85.0
998    88.0
999    80.0
Name: date, Length: 1000, dtype: float64

In [24]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [25]:
# Converting to datetime datatypes
time['date'] = pd.to_datetime(time['date'])
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [26]:
time['hour'] = time['date'].dt.hour
time['minute'] = time['date'].dt.minute
time['seconds'] = time['date'].dt.second

time.head()

,date,msg,hour,minute,seconds
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [27]:
# Extracting only time part from date column

time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,minute,seconds,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [28]:
# Time difference

today - time['date']

0     4570 days 20:48:45.435283
1     4434 days 21:58:45.435283
2     4920 days 21:17:45.435283
3     4222 days 21:07:45.435283
4     4619 days 22:27:45.435283
                 ...
995   5209 days 20:48:45.435283
996   4530 days 22:24:45.435283
997   4995 days 22:01:45.435283
998   5111 days 22:04:45.435283
999   4383 days 22:13:45.435283
Name: date, Length: 1000, dtype: timedelta64[ns]

In [30]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.949229e+08
1      3.831767e+08
2      4.251647e+08
3      3.648569e+08
4      3.991625e+08
           ...
995    4.501325e+08
996    3.914727e+08
997    4.316473e+08
998    4.416699e+08
999    3.787712e+08
Name: date, Length: 1000, dtype: float64

In [31]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.582049e+06
1      6.386279e+06
2      7.086078e+06
3      6.080948e+06
4      6.652708e+06
           ...
995    7.502209e+06
996    6.524545e+06
997    7.194122e+06
998    7.361165e+06
999    6.312854e+06
Name: date, Length: 1000, dtype: float64

In [32]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      109700.812621
1      106437.979288
2      118101.295954
3      101349.129288
4      110878.462621
           ...
995    125036.812621
996    108742.412621
997    119902.029288
998    122686.079288
999    105214.229288
Name: date, Length: 1000, dtype: float64