In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [5]:
headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/137.0.0.0 Safari/537.36"
    )
}
webpage = requests.get('https://www.ambitionbox.com/list-of-companies?page=1',headers=headers).text
# webpage contains the whole HTML of that page

In [6]:
soup = BeautifulSoup(webpage,'lxml')

In [17]:
print(soup.prettify())

_IncompleteInputError: incomplete input (3435108921.py, line 1)

In [16]:
for i in soup.find_all('h2'):
    print(i.text.strip())

Companies in India
TCS
Accenture
Wipro
Cognizant
Capgemini
HDFC Bank
Infosys
HCLTech
ICICI Bank
Tech Mahindra
Genpact
TP
Jio
Axis Bank
Concentrix Corporation
Amazon
Reliance Retail
iEnergizer
LTIMindtree
IBM
Popular Collections by Industries
Popular Collections by Cities
Popular Collections by Roles

In [21]:
for i in soup.find_all('div',style='height:auto;'):
    print(i.text.strip())

3.3
3.7
3.6
3.7
3.6
3.8
3.5
3.4
3.9
3.3
3.6
3.9
4.4
3.6
3.6
3.9
3.9
4.6
3.6
3.9

In [29]:
div = soup.find_all("div", class_="companyCardWrapper__tertiaryInformation")
for divs in div:
    first_a = divs.find("a")
    first_span = first_a.find("span")
    print(first_span.text.strip())

1.2L
74.3k
65.7k
62k
54k
53.1k
49.3k
46.5k
46.3k
43.8k
42.8k
39.1k
33.8k
33.7k
32.6k
31.8k
27.6k
27.3k
26.7k
26k

# Or we can simply go through the whole div and get content each time

In [36]:
name=[]
rating=[]
div = soup.find_all('div',class_='companyCardWrapper')

for i in div:
    name.append(i.find('h2',class_='companyCardWrapper__companyName').text.strip())
    a = i.find('a',class_='companyCardWrapper__ActionWrapper')
    rating.append(a.find('span',class_='companyCardWrapper__ActionCount').text.strip())

['TCS',
 'Accenture',
 'Wipro',
 'Cognizant',
 'Capgemini',
 'HDFC Bank',
 'Infosys',
 'HCLTech',
 'ICICI Bank',
 'Tech Mahindra',
 'Genpact',
 'TP',
 'Jio',
 'Axis Bank',
 'Concentrix Corporation',
 'Amazon',
 'Reliance Retail',
 'iEnergizer',
 'LTIMindtree',
 'IBM']

In [37]:
d = {'name':name, 'rating':rating}
df = pd.DataFrame(d)
df

                      name rating
0                      TCS   1.2L
1                Accenture  74.3k
2                    Wipro  65.7k
3                Cognizant    62k
4                Capgemini    54k
5                HDFC Bank  53.1k
6                  Infosys  49.3k
7                  HCLTech  46.5k
8               ICICI Bank  46.3k
9            Tech Mahindra  43.8k
10                 Genpact  42.8k
11                      TP  39.1k
12                     Jio  33.8k
13               Axis Bank  33.7k
14  Concentrix Corporation  32.6k
15                  Amazon  31.8k
16         Reliance Retail  27.6k
17              iEnergizer  27.3k
18             LTIMindtree  26.7k
19                     IBM    26k

# And now to access all the pages of the website

In [41]:
final = pd.DataFrame()

for j in range(1,3):
    url = 'https://www.ambitionbox.com/list-of-companies?page={}'.format(j)
    headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/137.0.0.0 Safari/537.36"
        )        
    }
    webpage = requests.get(url,headers=headers).text
    soup = BeautifulSoup(webpage,'lxml')
    name=[]
    rating=[]
    div = soup.find_all('div',class_='companyCardWrapper')

    for i in div:
        name.append(i.find('h2',class_='companyCardWrapper__companyName').text.strip())
        a = i.find('a',class_='companyCardWrapper__ActionWrapper')
        rating.append(a.find('span',class_='companyCardWrapper__ActionCount').text.strip())
        d = {'name':name, 'rating':rating}
        
        df = pd.DataFrame(d)

    final = pd.concat([final, df], ignore_index=True)


final

                       name rating
0                       TCS   1.2L
1                 Accenture  74.3k
2                     Wipro  65.7k
3                 Cognizant    62k
4                 Capgemini    54k
5                 HDFC Bank  53.1k
6                   Infosys  49.3k
7                   HCLTech  46.5k
8                ICICI Bank  46.3k
9             Tech Mahindra  43.8k
10                  Genpact  42.8k
11                       TP  39.1k
12                      Jio  33.8k
13                Axis Bank  33.7k
14   Concentrix Corporation  32.6k
15                   Amazon  31.8k
16          Reliance Retail  27.6k
17               iEnergizer  27.3k
18              LTIMindtree  26.7k
19                      IBM    26k
20   HDB Financial Services    26k
21  Larsen & Toubro Limited  24.1k
22                 Deloitte  23.6k
23      Kotak Mahindra Bank  22.7k
24      Reliance Industries  20.4k
25            Vodafone Idea  17.7k
26            Bharti Airtel  17.2k
27                   BYJU'S  16.4k
28                      WNS  15.4k
29          IDFC FIRST Bank  14.9k
30            Ernst & Young  14.8k
31            IndusInd Bank  14.4k
32    AU Small Finance Bank  14.4k
33              Tata Motors  14.3k
34            Bajaj Finserv  13.3k
35          Muthoot FinCorp  13.2k
36                 Flipkart  13.1k
37                      PwC  12.9k
38                HDFC Life  12.2k
39      Mahindra & Mahindra  12.2k