In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

import seaborn as sns

In [5]:
df = pd.read_csv('titanic.csv',usecols=['Age','Pclass','SibSp','Parch','Survived'])
df.head()

   Survived  Pclass   Age  SibSp  Parch
0         0       3  22.0      1      0
1         1       1  38.0      1      0
2         1       3  26.0      0      0
3         1       1  35.0      1      0
4         0       3  35.0      0      0

In [6]:
df.dropna(inplace=True)

In [10]:
X = df.iloc[:,1:5]
y=df.iloc[:,0]

X.head()

   Pclass   Age  SibSp  Parch
0       3  22.0      1      0
1       1  38.0      1      0
2       3  26.0      0      0
3       1  35.0      1      0
4       3  35.0      0      0

In [11]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))

np.float64(0.6933333333333332)

### Applying Feature Construction

In [12]:
X['Family_size'] = X['SibSp'] + X['Parch'] + 1
X.head()

   Pclass   Age  SibSp  Parch  Family_size
0       3  22.0      1      0            2
1       1  38.0      1      0            2
2       3  26.0      0      0            1
3       1  35.0      1      0            2
4       3  35.0      0      0            1

In [13]:
def myfunc(num):
    if num == 1:
        # Alone 
        return 0
    elif num > 1 and num <= 4:
        # Small Family
        return 1
    else:
        # Large Family
        return 2

In [15]:
X['Family_type'] = X["Family_size"].apply(myfunc)
X.head()

   Pclass   Age  SibSp  Parch  Family_size  Family_type
0       3  22.0      1      0            2            1
1       1  38.0      1      0            2            1
2       3  26.0      0      0            1            0
3       1  35.0      1      0            2            1
4       3  35.0      0      0            1            0

In [17]:
X.drop(columns=['SibSp','Parch','Family_size'],inplace=True)
X.head()

   Pclass   Age  Family_type
0       3  22.0            1
1       1  38.0            1
2       3  26.0            0
3       1  35.0            1
4       3  35.0            0

In [18]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))

np.float64(0.7003174603174602)

# Feature Spliting

In [19]:
df = pd.read_csv('titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [20]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [21]:
df['Title'] = df['Name'].str.split(',',expand=True)[1].str.split('.',expand=True)[0]
df[['Title','Name']]

     Title                                               Name
0       Mr                            Braund, Mr. Owen Harris
1      Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
2     Miss                             Heikkinen, Miss. Laina
3      Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4       Mr                           Allen, Mr. William Henry
..     ...                                                ...
886    Rev                              Montvila, Rev. Juozas
887   Miss                       Graham, Miss. Margaret Edith
888   Miss           Johnston, Miss. Catherine Helen "Carrie"
889     Mr                              Behr, Mr. Karl Howell
890     Mr                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [23]:
(df.groupby('Title')['Survived'].mean()).sort_values(ascending=False)

Title
the Countess    1.000000
Mlle            1.000000
Sir             1.000000
Ms              1.000000
Lady            1.000000
Mme             1.000000
Mrs             0.792000
Miss            0.697802
Master          0.575000
Col             0.500000
Major           0.500000
Dr              0.428571
Mr              0.156673
Jonkheer        0.000000
Rev             0.000000
Don             0.000000
Capt            0.000000
Name: Survived, dtype: float64

We can analyse that Mrs had the highest survival rate and then Ms

In [24]:
df['IsMarried'] = 0
df['IsMarried'].loc[df['Title'] == 'Mrs'] = 1

C:\Users\DELL\AppData\Local\Temp\ipykernel_26580\3527651622.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['IsMarried'].loc[df['Title'] == 'Mrs'] = 1
C:\Users\DELL\AppData\Local\Temp\ipykernel_26580\3527651622.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['IsMarried'].loc[df['Title'] == 'Mrs'] = 1

In [25]:
df['IsMarried']

0      0
1      0
2      0
3      0
4      0
      ..
886    0
887    0
888    0
889    0
890    0
Name: IsMarried, Length: 891, dtype: int64